name: Basic tests
on: [push, pull_request]

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['2.x', '3.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install gcc-multilib
      - name: Install bitnesslib
        run: |
          pip install .[test]
      - name: Run tests
        run: |
          pytest tests/
